function [a,b,c,d,e,f,g] = autoGen_sixOrderPolyCoeff(T,p0,v0,a0,pm,p1,v1,a1)
%AUTOGEN_SIXORDERPOLYCOEFF
%    [A,B,C,D,E,F,G] = AUTOGEN_SIXORDERPOLYCOEFF(T,P0,V0,A0,PM,P1,V1,A1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    03-Nov-2021 17:19:40

a = p0;
if nargout > 1
    b = v0;
end
if nargout > 2
    c = a0./2.0;
end
if nargout > 3
    t2 = T.^2;
    t4 = pm.*3.84e+2;
    t3 = a1.*t2;
    d = 1.0./T.^3.*(p0.*8.4e+1+p1.*4.4e+1-pm.*1.28e+2+t3+T.*v0.*3.2e+1-T.*v1.*1.2e+1+a0.*t2.*5.0).*(-1.0./2.0);
end
if nargout > 4
    t5 = -t4;
    e = (1.0./t2.^2.*(p0.*2.22e+2+p1.*1.62e+2+t3.*4.0+t5+T.*v0.*7.6e+1-T.*v1.*4.6e+1+a0.*t2.*9.0))./2.0;
end
if nargout > 5
    f = 1.0./T.^5.*(p0.*2.04e+2+p1.*1.8e+2+t3.*5.0+t5+T.*v0.*6.6e+1-T.*v1.*5.4e+1+a0.*t2.*7.0).*(-1.0./2.0);
end
if nargout > 6
    g = 1.0./t2.^3.*(p0.*3.2e+1+p1.*3.2e+1-pm.*6.4e+1+t3+T.*v0.*1.0e+1-T.*v1.*1.0e+1+a0.*t2);
end
