function [dP3,dP5] = autoGen_feetVel(x,y,q1,q2,q3,q4,q5,dx,dy,dq1,dq2,dq3,dq4,dq5,l1,l2,l3,l4,l5)
%AUTOGEN_FEETVEL
%    [DP3,DP5] = AUTOGEN_FEETVEL(X,Y,Q1,Q2,Q3,Q4,Q5,DX,DY,DQ1,DQ2,DQ3,DQ4,DQ5,L1,L2,L3,L4,L5)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Mar-2023 20:48:32

t2 = q2+q3;
t3 = q4+q5;
t4 = cos(t2);
t5 = cos(t3);
t6 = sin(t2);
dP3 = [dx+dq2.*(l3.*t4+l2.*cos(q2))+dq3.*l3.*t4;dy+dq2.*(l3.*t6+l2.*sin(q2))+dq3.*l3.*t6];
if nargout > 1
    t7 = sin(t3);
    dP5 = [dx+dq4.*(l5.*t5+l4.*cos(q4))+dq5.*l5.*t5;dy+dq4.*(l5.*t7+l4.*sin(q4))+dq5.*l5.*t7];
end
