function obj = autoGen_objFunc(u1,u2,u3,u4,fx,fy)
%AUTOGEN_OBJFUNC
%    OBJ = AUTOGEN_OBJFUNC(U1,U2,U3,U4,FX,FY)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Mar-2023 20:48:31

obj = fx.^2./1.0e+4+fy.^2./1.0e+4+u1.^2+u2.^2+u3.^2+u4.^2;
