function [MM,rhs] = autoGen_dynamics(x,y,q1,q2,q3,q4,q5,dx,dy,dq1,dq2,dq3,dq4,dq5,u1,u2,u3,u4,fx,fy,m1,m2,m3,m4,m5,I1,I2,I3,I4,I5,l1,l2,l3,l4,l5,c1,c2,c3,c4,c5,g)
%AUTOGEN_DYNAMICS
%    [MM,RHS] = AUTOGEN_DYNAMICS(X,Y,Q1,Q2,Q3,Q4,Q5,DX,DY,DQ1,DQ2,DQ3,DQ4,DQ5,U1,U2,U3,U4,FX,FY,M1,M2,M3,M4,M5,I1,I2,I3,I4,I5,L1,L2,L3,L4,L5,C1,C2,C3,C4,C5,G)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Mar-2023 20:48:30

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q3);
t10 = sin(q4);
t11 = sin(q5);
t12 = q2+q3;
t13 = q4+q5;
t14 = c3.^2;
t15 = c5.^2;
t16 = dq1.^2;
t17 = dq2.^2;
t18 = dq3.^2;
t19 = dq4.^2;
t20 = dq5.^2;
t39 = m1+m2+m3+m4+m5;
t21 = cos(t12);
t22 = cos(t13);
t23 = sin(t12);
t24 = sin(t13);
t25 = c1.*m1.*t2;
t26 = c2.*m2.*t3;
t27 = c4.*m4.*t5;
t28 = c1.*m1.*t7;
t29 = c2.*m2.*t8;
t30 = c4.*m4.*t10;
t31 = m3.*t14;
t32 = m5.*t15;
t33 = l2.*t3.*2.0;
t34 = l4.*t5.*2.0;
t35 = l2.*t8.*2.0;
t36 = l4.*t10.*2.0;
t37 = c3.*l2.*m3.*t4;
t38 = c5.*l4.*m5.*t6;
t40 = -t25;
t41 = -t28;
t42 = c3.*t21.*2.0;
t43 = c5.*t22.*2.0;
t44 = c3.*t23.*2.0;
t45 = c5.*t24.*2.0;
t46 = c3.*m3.*t21;
t47 = c5.*m5.*t22;
t48 = c3.*m3.*t23;
t49 = c5.*m5.*t24;
t54 = I3+t31+t37;
t55 = I5+t32+t38;
t50 = t33+t42;
t51 = t34+t43;
t52 = t35+t44;
t53 = t36+t45;
t56 = (m3.*t50)./2.0;
t57 = (m5.*t51)./2.0;
t58 = (m3.*t52)./2.0;
t59 = (m5.*t53)./2.0;
t60 = t26+t56;
t61 = t27+t57;
t62 = t29+t58;
t63 = t30+t59;
MM = reshape([t39,0.0,t40,t60,t46,t61,t47,0.0,t39,t41,t62,t48,t63,t49,t40,t41,I1+c1.^2.*m1,0.0,0.0,0.0,0.0,t60,t62,0.0,I2+t37+t54+c2.^2.*m2+l2.^2.*m3,t54,0.0,0.0,t46,t48,0.0,t54,I3+t31,0.0,0.0,t61,t63,0.0,0.0,0.0,I4+t38+t55+c4.^2.*m4+l4.^2.*m5,t55,t47,t49,0.0,0.0,0.0,t55,I5+t32],[7,7]);
if nargout > 1
    rhs = [fx+t17.*t29+t19.*t30+t16.*t41+t17.*t48+t18.*t48+t19.*t49+t20.*t49+dq2.*dq3.*m3.*t44+dq4.*dq5.*m5.*t45+l2.*m3.*t8.*t17+l4.*m5.*t10.*t19;fy-g.*m1-g.*m2-g.*m3-g.*m4-g.*m5+t16.*t25-t17.*t26-t19.*t27-t17.*t46-t18.*t46-t19.*t47-t20.*t47-dq2.*dq3.*t46.*2.0-dq4.*dq5.*t47.*2.0-l2.*m3.*t3.*t17-l4.*m5.*t5.*t19;g.*t28;u1-g.*t29-g.*t48+fx.*(l2.*t3+l3.*t21)+fy.*(l2.*t8+l3.*t23)-g.*l2.*m3.*t8+c3.*l2.*m3.*t9.*t18+c3.*dq2.*dq3.*l2.*m3.*t9.*2.0;u2-c3.*m3.*(g.*t23+l2.*t9.*t17)+fx.*l3.*t21+fy.*l3.*t23;u3-g.*t30-g.*t49-g.*l4.*m5.*t10+c5.*l4.*m5.*t11.*t20+c5.*dq4.*dq5.*l4.*m5.*t11.*2.0;u4-c5.*m5.*(g.*t24+l4.*t11.*t19)];
end
