function [P,Gvec] = autoGen_kinematicsPoints(x,y,q1,q2,q3,q4,q5,l1,l2,l3,l4,l5,c1,c2,c3,c4,c5)
%AUTOGEN_KINEMATICSPOINTS
%    [P,GVEC] = AUTOGEN_KINEMATICSPOINTS(X,Y,Q1,Q2,Q3,Q4,Q5,L1,L2,L3,L4,L5,C1,C2,C3,C4,C5)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Mar-2023 20:48:32

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q4);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q4);
t8 = q2+q3;
t9 = q4+q5;
t10 = l2.*t3;
t11 = l4.*t4;
t12 = cos(t8);
t13 = cos(t9);
t14 = l2.*t6;
t15 = l4.*t7;
t16 = sin(t8);
t17 = sin(t9);
t18 = -t10;
t19 = -t11;
P = [x;y;x-l1.*t5;y+l1.*t2;t14+x;t18+y;t14+x+l3.*t16;t18+y-l3.*t12;t15+x;t19+y;t15+x+l5.*t17;t19+y-l5.*t13];
if nargout > 1
    Gvec = [x-c1.*t5;y+c1.*t2;x+c2.*t6;y-c2.*t3;t14+x+c3.*t16;t18+y-c3.*t12;x+c4.*t7;y-c4.*t4;t15+x+c5.*t17;t19+y-c5.*t13];
end
