function [P3,P5] = autoGen_feetPos(x,y,q1,q2,q3,q4,q5,l1,l2,l3,l4,l5)
%AUTOGEN_FEETPOS
%    [P3,P5] = AUTOGEN_FEETPOS(X,Y,Q1,Q2,Q3,Q4,Q5,L1,L2,L3,L4,L5)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Mar-2023 20:48:31

t2 = q2+q3;
P3 = [x+l2.*sin(q2)+l3.*sin(t2);y-l2.*cos(q2)-l3.*cos(t2)];
if nargout > 1
    t3 = q4+q5;
    P5 = [x+l4.*sin(q4)+l5.*sin(t3);y-l4.*cos(q4)-l5.*cos(t3)];
end
