function [ddx,ddq] = autoGen_cartPoleDynamics(x,q,dx,dq,u,M,m,g,l)
%AUTOGEN_CARTPOLEDYNAMICS
%    [DDX,DDQ] = AUTOGEN_CARTPOLEDYNAMICS(X,Q,DX,DQ,U,M,M,G,L)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    07-Mar-2023 14:35:33

t2 = cos(q);
t3 = sin(q);
t4 = dq.^2;
t5 = t2.^2;
t6 = m.*t5;
t7 = -t6;
t8 = M+m+t7;
t9 = 1.0./t8;
ddx = t9.*(u+g.*m.*t2.*t3+l.*m.*t3.*t4);
if nargout > 1
    ddq = -(t9.*(t2.*u+M.*g.*t3+g.*m.*t3+l.*m.*t2.*t3.*t4))./l;
end
