function [p1x,p1y,p2x,p2y] = autoGen_cartPoleKinematics(x,q,l)
%AUTOGEN_CARTPOLEKINEMATICS
%    [P1X,P1Y,P2X,P2Y] = AUTOGEN_CARTPOLEKINEMATICS(X,Q,L)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    07-Mar-2023 14:35:34

p1x = x;
if nargout > 1
    p1y = 0.0;
end
if nargout > 2
    p2x = x+l.*sin(q);
end
if nargout > 3
    p2y = -l.*cos(q);
end
